---
apiVersion: v1
kind: Service
metadata:
  name: spotify-web
  namespace: spotify
spec:
  selector:
    app: spotify-web
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-web
  namespace: spotify
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - spotify.codeofficer.com
      secretName: spotify-web-tls
  rules:
    - host: spotify.codeofficer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spotify-web
                port:
                  number: 3000
